/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/book` | `/book`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/character` | `/character`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/journal-entry` | `/journal-entry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/phone` | `/phone`; params?: Router.UnknownInputParams; } | { pathname: `/components/auth/LoginForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/auth/RegisterForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/button`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/form-field`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/input`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/label`; params?: Router.UnknownInputParams; } | { pathname: `/lib/utils`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/book` | `/book`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/character` | `/character`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/journal-entry` | `/journal-entry`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/phone` | `/phone`; params?: Router.UnknownOutputParams; } | { pathname: `/components/auth/LoginForm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/auth/RegisterForm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/button`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/form-field`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/input`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/label`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/utils`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/agenda${`?${string}` | `#${string}` | ''}` | `/agenda${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/book${`?${string}` | `#${string}` | ''}` | `/book${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/character${`?${string}` | `#${string}` | ''}` | `/character${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/journal-entry${`?${string}` | `#${string}` | ''}` | `/journal-entry${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/phone${`?${string}` | `#${string}` | ''}` | `/phone${`?${string}` | `#${string}` | ''}` | `/components/auth/LoginForm${`?${string}` | `#${string}` | ''}` | `/components/auth/RegisterForm${`?${string}` | `#${string}` | ''}` | `/components/ui/button${`?${string}` | `#${string}` | ''}` | `/components/ui/form-field${`?${string}` | `#${string}` | ''}` | `/components/ui/input${`?${string}` | `#${string}` | ''}` | `/components/ui/label${`?${string}` | `#${string}` | ''}` | `/lib/utils${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/book` | `/book`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/character` | `/character`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/journal-entry` | `/journal-entry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/phone` | `/phone`; params?: Router.UnknownInputParams; } | { pathname: `/components/auth/LoginForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/auth/RegisterForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/button`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/form-field`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/input`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/label`; params?: Router.UnknownInputParams; } | { pathname: `/lib/utils`; params?: Router.UnknownInputParams; };
    }
  }
}
